import localFont from "next/font/local";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import SessionWrapper from "@/components/auth/SessionWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <head>
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          ></link>
        </head>
        <body className="bg-neutral-800">
          <NextTopLoader color="#36BFB1" />
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
